### ISSUE TITLE
Depends on jts-infer which makes strange guesses

### ISSUE THREAD

**Issue by danfowler** [okfn/datapackage-init-js#19]
`jts-infer` is no longer maintained and makes incorrect type guesses when a given column has empty fields.  Issue fixed in https://github.com/scienceai/jsonld-context-infer.

see also: https://github.com/sballesteros/jts-infer/issues/3

**Comment by rgrp** [comment]
@danfowler we should be depending on https://github.com/okfn/json-table-schema-infer which we forked a while back and maintain.

**Comment by pwalsh** [comment]
@danfowler let's sync on this Monday as there is an even more recent package. we can implement a deprecation strategy for the various different attempts over the years.

**Comment by danfowler** [comment]
OK

**Comment by pwalsh** [comment]
@danfowler we started https://github.com/okfn/jsontableschema-js which is more or less API compatible with https://github.com/okfn/jsontableschema-py, and we want to maintain this going forward. 

We need to approach this as part of our wider work on frictionless data - I've already made some notes on this in terms of how we move forward updating *all* our libs in Python and Javascript.

As a first, immediate step, see if you get better results with https://github.com/okfn/jsontableschema-js and we can swap this out, but we need to go a bit further than that with some integration work.

**Comment by rgrp** [comment]
@pwalsh why not start from https://github.com/okfn/json-table-schema-infer which is already compatible with datapackage-init. In either case how is this going?

**Comment by pwalsh** [comment]
@rgrp https://github.com/okfn/jsontableschema-js was simply an attempt to bring the Javascript libs for JSON Table Schema up-to-date with the spec, and more or less API compatible with the Python lib of the same. https://github.com/okfn/json-table-schema-infer was directly referenced in the development of this and in hindsight we should have just updated that library.

**Comment by rgrp** [comment]
Can we deprecate one or other in favour of the other?

**Comment by pwalsh** [comment]
@rgrp yes we can and should have done so already. I'm adding it as an action for myself for early next week.
