### ISSUE TITLE
Needs helper text

### ISSUE THREAD

**Issue by sanjaypoyzer** [okfn/datapackage-init-js#6]
Right now, this tool can only really be used by people who know what they're doing. To be more intuitive, some info should be added.

Some questions I had while using it:

 - Which of these fields are required for the datapackage format?
 - What do these fields mean? (Particularly important considering how confusing "title" and "name".
 - A link back to the datapackage specs to answer any other questions would be good too.

**Comment by rgrp** [comment]
@sanjaypoyzer +1 - we are working on it.

**Comment by rgrp** [comment]
FIXED. @sanjaypoyzer see http://datapackagist.okfnlabs.org/ which is a much more powerful version of the demo app available since last year.
